import blogProfile from "assets/blogProfile.png";
const BlogData = [
  {
    blogId: 0,
    Category: "Technical",
    BlogHeading: "What is Kubernetes?",
    AboutBlog:
      "Kubernetes is open-source software for deploying and managing those containers at scale. Modern applications are increasingly built using containers, which are microservices packaged with their dependencies and configurations.",
    imgsrc: blogProfile,
    FullBlog: [
      "Kubernetes :-",
      "Kubernetes is open-source software for deploying and managing those containers at scale. Modern applications are increasingly built using containers, which are microservices packaged with their dependencies and configurations.",
      "How Kubernetes Works :-",
      "As applications grow to span multiple containers deployed across multiple servers, operating them becomes more complex. To manage this complexity, Kubernetes provides an open source API that controls how and where those containers will run. Kubernetes orchestrates clusters of virtual machines and schedules containers to run on those virtual machines based on their available compute resources and the resource requirements of each container. Containers are grouped into pods, the basic operational unit for Kubernetes and those pods scale to your desired state. Kubernetes also automatically manages service discovery, incorporates load balancing, tracks resource allocation and scales based on compute utilization. And, it checks the health of individual resources and enables apps to self-heal by automatically restarting or replicating containers.",
      "Why use Kubernetes?",
      "Keeping containerized apps up and running can be complex because they often involve many containers deployed across different machines. Kubernetes provides a way to schedule and deploy those containers — plus scale them to your desired state and manage their lifecycles. Use Kubernetes to implement your container-based applications in a portable, scalable and extensible way. Azure Kubernetes Service (AKS) is a managed container orchestration service, based on the open source Kubernetes system, which is available on the Microsoft Azure public cloud Deploy and manage containerized applications more easily with a fully managed Kubernetes service. Azure Kubernetes Service (AKS) offers server less Kubernetes, an integrated continuous integration and continuous delivery (CI/CD) experience and enterprise-grade security and governance. Unite your development and operations teams on a single platform to rapidly build, deliver and scale applications with confidence.",
      "Common uses for Azure Kubernetes Service (AKS)",
      "1.Lift and Shift to container with AKS",
      "Easily migrate existing application to container(s) and run within the Azure managed Kubernetes service (AKS).",
      "2.Microservices with AKS",
      "Use AKS to simplify the deployment and management of microservices based architecture. AKS streamlines horizontal scaling, self-healing, load balancing, secret management.",
      "3.Secure DevOps with AKS",
      "DevOps and Kubernetes are better together. Implementing secure DevOps together with Kubernetes on Azure, you can achieve the balance between speed and security and deliver code faster at scale.",
      "4.Bursting from AKS with ACI",
      "Use the AKS virtual node to provision pods inside ACI that start in seconds. This enables AKS to run with just enough capacity for your average workload.",
      "5.Machine Learning model training with AKS:-",
      "Using large datasets ,training of models is a complex and resource intensive task. Use familiar tools such as Tensorflow and Kubeflow to simplify training of Machine Learning models.",
      "6.Data Streaming Scenario:-",
      "Use AKS to easily ingest & process a real-time data stream with millions of data points collected via sensors. Perform fast analysis and computations to develop insights into complex scenarios quickly.",
    ],
    Name: "Tamanna Verma",
    BlogDate: "May 15, 2021",
  },
  {
    blogId: 1,
    Category: "Technical",
    BlogHeading: "Machine Learning is Driving Innovation at Uber.",
    AboutBlog:
      "To know what is machine learning ..first, let’s be aware of what data science is?  Data Science is a branch of Computer Science that contains Machine Learning /Deep Learning and ....",
    FullBlog: [
      "Some of us really don’t know that what is machine learning actually …",
      "To know what is machine learning ..first, let’s be aware of what data science is?",
      "Data Science is a branch of Computer Science that contains Machine Learning /Deep Learning and many more. It helps to predict future data with the help of historical data by training the machine or by giving intelligence to the machine. Uber is one of the most successful startups of all time. The idea of Uber was born when its co-founder Garrett Camp had to pay $800 to hire a private driver on New Year’s Eve. The idea was converted into a business called UberCabs in 2009. Initially Uber offered rides only in black luxury cars, and three years later, UberX was rolled out. UberX allowed people to drive for Uber using their own cars. The business took off, and the startup joined the eight-figure decacorn club being valued at over $70 billion in less than 10 years. Uber gives about 1 million rides per day and 14,000 rides per minute and adds about 50,000 drivers per month. Giving customers exactly what they want at a reasonable cost is one of the important reasons for Uber’s success. Uber’s machine learning algorithms play a crucial role in helping the company predict customer needs.",
      "What is machine learning?",
      "Uber",
      "Traditionally, humans played a key role in analyzing data patterns and building systems on top of these patterns. When the volumes of data surpassed the ability to manually process it, the need for automation was triggered. This need eventually gave birth to machine learning. In a nutshell, machine learning is about making computers answer questions based on data patterns. We see machine learning in almost all the systems around us today. For example, when you watch videos of a particular celebrity on YouTube, the system understands that you enjoy content related to that celebrity. The system then recommends similar videos. Here, YouTube’s machine learning systems learn from your browsing data and predicts your likes. The same logic is applied in systems like Facebook’s photo tagging recommendations, auto-correct and text prediction in mobile phone keyboards, and so much more. Machine learning is at the core of Uber",
      "Uber’s decision-making is completely data-driven with machine learning at its core. Uber leverages machine learning in many ways to make the customer experience better. For example, when you tap the destination field, the app shows you suggestions based on your ride history and frequently traveled destinations. Here are some interesting ways in which Uber leverages machine learning to streamline the business process. Bridging the supply-demand gap",
      "Based on historical data, Uber predicts the time and areas of demand. The system uses these predictions to alert drivers of the areas with upcoming demand. This way, Uber makes sure that there are enough cabs in the predicted areas of demand and bridges the supply-demand gap. Demand prediction systems enable the app to slightly increase the prices during peak hours, eventually increasing profitability. Customers don’t wait when cabs are not instantly available, they just book a ride from a different service. Customer retention is very important for a service like ride-hailing. Getting a new customer can take up to six to seven times more effort than retaining an existing customer. The supply-demand gap can affect customer retention to a great extent. But Uber’s machine learning based demand predictions prevent Uber from losing customers to its competitors.",
      "Reduction in ETA",
      "The time wasted in road traffic is one of the most frustrating problems in the urbanized areas. This gets worse when cabs take longer to reach the pickup point. But, Uber’s machine learning algorithms have a solution for this issue too. By predicting demand and keeping cabs ready, Uber reduces the expected time arrival (ETA) when a customer makes a booking. By reducing a lot of wait time, Uber always makes the customer experience better. The perfect blend of customer satisfaction, loyalty programs, and referral bonuses has resulted in a massive expansion in the customer base just through word of mouth.",
      "Route optimization",
      "Conventional ride-hailing systems require the driver to make assumption-based route choices. This method is not reliable because the travel duration through the same route might change based on traffic jams, weather conditions, and road maintenance schedules. But Uber’s machine learning system updates the app with the conditions in every route and suggests the fastest route to the driver. This way, Uber helps its drivers avoid congestion and enables faster rides. Besides making the customers happy, faster rides also enable drivers to get additional time to take on more rides.",
      "AI-based one-click chat",
      "Riders tend to message drivers while they wait for the cab. Most of the time, riders do this to check the status when they see the cab barely moving in the app. It is difficult for drivers to type a reply while driving. So Uber came up with an artificial intelligence-based concept called the “one-click chat.” The one-click chat leverages natural language processing and machine learning techniques to predict responses to common messages. This way, drivers can easily respond to the messages by just clicking on one of the suggested replies.",
      "Uber Pool",
      "During rush hours, it is difficult to make individual cabs available for everyone. But ridesharing solves this problem by matching the riders heading in the same direction. Also, the pooling feature makes the rides more economical by reducing the fares by 25 percent to 40 percent. Machine learning algorithms decide which rider to drop first based on the data gathered from maps. Also, the app uses historical data and patterns to understand peak hours and surge prices accordingly.",
      "Machine learning in Uber’s robotaxi",
      "Shutterstock",
      "Autonomous vehicles are the future of the transportation industry. Uber is one of the super-successful companies that is dumping millions into driverless cars. Uber’s robotaxi aims to compete with Google’s Waymo and General Motor’s Cruise. Uber rolled out their autonomous cars in 2015 when self-driving cars were only thought about as fiction. These autonomous cars, however, had a driver take control when things get rough. Machine learning is the core technology behind the decision-making of Uber’s driverless cars. It is the machine learning algorithms that harness the data gathered from various sensors like lidar, radar, and cameras deployed in the vehicle and direct the actuators accordingly. Sensors will only be able to detect the obstacles on the road. It is the machine learning algorithms that help the vehicles figure out if the obstacle is a pedestrian or an object or another vehicle. Based on this analysis, the cars decide whether to use the horn or to break the speed or to take a diversion. This type of machine learning is called machine vision. Uber: Innovation despite scandals. Uber is not just about hiring vehicles but innovation. Uber has been often plagued with scandals, regulatory troubles, and lawsuits. In 2016, Uber didn’t make any profit at all. Uber was once boycotted by some celebrities in the United States who also tried to spread the idea using the hashtag #DeleteUber. Uber was sued by Google’s parent company Alphabet because its former employee Anthony Levandowski allegedly stole some files when he was working with Google and used the data for Uber’s project. Despite these setbacks, Uber always managed to keep moving forward with innovative ideas like self-driving cars, hot-air balloon transportation, food delivery services, Uber boats, and even a helicopter service called the UberCHOPPER. Uber even has plans of rolling out flying taxis. The company seems to be quite serious about its future project called “Elevate,” which aims to bring aviation to everyday people. This ambitious plan will be implemented within the next decade.",
    ],
    imgsrc: blogProfile,
    Name: "Tamanna Verma",
    BlogDate: "May 15, 2021",
  },
  {
    blogId: 2,
    Category: "Technical",
    BlogHeading: "How Amazon.com use AWS?",
    AboutBlog:
      "Amazon Web Services (AWS) is an evolving cloud computing platform provided by Amazon. It provides a mix of infrastructure as a service (IaaS), Platform as a service (PaaS), and Packaged software as a service (SaaS) offerings.",
    imgsrc: blogProfile,
    FullBlog: [
      "Today Amazon.com is an online retailer, manufacturer of electronic book readers, and Web services provider that became the iconic example of electronic commerce. Its headquarters are in Seattle, Washington.",
      "History of Amazon",
      "Amazon started in 1995 as a book retailer, it was a site that only sold books. Within a month of starting the company, it already shipped books to over 40 different countries. Since then, Amazon has become one of the world’s largest e-commerce companies. How exactly did Amazon pull off such impressive results?",
      "Innovation:",
      "Amazon’s success largely stems from its innovative technologies and practices, many of which were championed by its CEO, Jeff Bezos. Consider the Echo, Amazon’s impressive voice command device. The echo can be used to play songs, research your favorite sports teams, and even check the weather with a few spoken words. This innovative technology was a huge investment for the e-commerce giant -one that encouraged the development of such exceptional results. Over 22 million Echo units were sold in 2017 alone. Amazon’s progressive mindset doesn’t always bear fruit, but accomplishments like the Echo prove that innovation can yield impressive results for e-commerce companies.",
      "CUSTOMER SERVICE",
      "Because of its commitment to world-class customer service, Amazon has developed a range of helpful tools users can employ to track packages and quickly return or exchange ordered items, bringing simplicity and convenience to their online shopping experiences. Amazon’s Customer Service team has won multiple awards for its dedication to preventing and swiftly addressing problems for customers. One of Amazon’s overarching missions is to become the planet’s most customer-centric company and the brand’s dedication to this goal has paid dividends.",
      "EXECUTION",
      "Amazon gets everything right when executing customer orders. They select products and services that customers want and need and best places for distribution centers across the globe that allow them to quickly ship products. Amazon also has excellent vendor relationships that allow them to offer customers discounted pricing. They’re also looking to implement brick-and-mortar stores that will have the capability of same-day-delivery via drones!",
      "DIVERSIFICATION",
      "Starting off as an online bookstore, Amazon now offers everything from soup to nuts. Literally, a search of the site reveals over 3,000 listings for vegetable soup. Search the term “nuts” and you’ll see over 37,000 results. Amazon now carries products in music, books, electronics, health and beauty, automotive, grocery, and clothing. Business owners can contract with Amazon’s network of pros to get IT support, furniture assembly, and even A/V services. By diversifying its offerings, Amazon is continuously driving reach and relevance.",
      "OUTSTANDING USER EXPERIENCES",
      "A strong UX (Amazon’s User Experience) makes it easy for e-commerce customers to find what they’re looking for. That’s why Amazon employs a full UX team comprised of professionals in everything from user research and interaction design to web development. These UX experts collaborate with Amazon’s engineers, product managers, and executives to create seamless user experiences that drive customer conversions.",
      "MERGING DESIGN WITH CONTENT",
      "It’s no secret that long-tail content is a huge component of e-commerce CEO. You need large amounts of keyword-rich copy to increase the visibility of a page on search engines and which is why Amazon uses lengthy product descriptions and FAQs on its product pages. However, take a look at any product page on Amazon, and you’ll notice that this long-tail content doesn’t adversely affect its flow or UX. Amazon’s product copy is given less priority than important CTAs (such as the “Add to Cart” and “Buy Now” buttons). This seamless merging of design and content ensures that Amazon pages attract and convert relevant web traffic.",
      "AN “IN IT TO WIN IT” MINDSET",
      "Does anybody really remember when Amazon was unprofitable? If you’ve been around for a while, you might remember Bezos’ warning to investors that it would be a long time before they would see a return. Back in 1997, he told Inc. Magazine that Amazon would be unprofitable for a very long time. His “in it to win it” mindset kept the company pushing through new strategies until 2003 — when the company posted its first profit. No matter how you look at it, Amazon has grown up from a little online bookstore to an industry giant. You could even say Amazon created the industry for total domination.",
      "Overview of AWS",
      "Cloud computing has become an integral part of businesses across all industries. AWS is the most popular form. It improves efficiency and provides relief for any number of business practices. Back in the 2000s, businesses were completely dependent on purchased servers, and those servers had limited functionality and steep prices. Plus, a functioning server required countless validations. The more growth businesses experienced, the more servers and optimization practices they needed. Acquiring those items proved inefficient, and, sometimes, prohibitively expensive. The advantages of AWS have solved many of those problems. Companies using AWS have servers available instantly, and AWS provides various workloads, increased storage options, and enhanced security measures,",
      "What is AWS?",
      "To be able to answer “What is AWS?”, you must first understand that it’s a cloud provider. Among other features, cloud providers grant more storage flexibility and enhanced security measures. They also contain features you’d find at a local data center, like security, higher computing capacity, and database construction. Depending on your location, you can get other features like content caching. One of the advantages of AWS is that you get all 175+ cloud services on a pay-as-you-go basis. This means that you pay only for the services you use. And it works on a relative scale. That means the less you use it, the less you pay. And the more you use it, the less you pay per unit. (i.e., The price of each unit goes down with each new purchase.) Earlier AWS used to charge on an hourly basis but now AWS charges on a minute basis.",
      "That’s not all. Other advantages of AWS relate to the applications associated with it. The applications are reliable because they run on a safe and reliable infrastructure. Their on-demand infrastructure allows greater scalability. The design options available on the cloud permit large flexibility. Reading about real-world uses (and users) of Amazon Web Services (AWS) can help you understand what kinds of interesting and innovative things can be done with AWS. And it should come as no surprise to you that Amazon is a proud user of Amazon Web Services.",
      "A Brief History of AWS",
      "AWS was launched in 2002. The company wanted to sell its unused infrastructure as a service, or as an offering to customers. The idea was met with enthusiasm. Amazon launched its first AWS product in 2006. Four years later, in 2012, Amazon hosted a huge event focused on collecting customer input about AWS. The company still holds similar events, such as Reinvent, which allows customers to share feedback about AWS. In 2015, Amazon announced that its AWS revenue had reached $7.8 billion. Between then and 2016, AWS launched measures that helped customers migrate their services to AWS. Those measures, along with the public’s growing appreciation of AWS’s features, induced further economic growth. Amazon’s revenue increased to $12.2 billion in 2016. Today, AWS offers customers 160 products and services. That number will likely increase, given the rate at which Amazon builds upon and tweaks AWS. Let us now improve our understanding of what AWS is by looking into the services of the amazon web services (AWS). Understanding AWS and Its Services",
      "AWS Services",
      "Since it came into existence, AWS has become an essential cloud computing technology. Here are some of AWS’s essential offerings:",
      "Amazon S3",
      "This tool is used for internet back up, and it’s the cheapest storage option in the object-storage category. The best part: you can retrieve stored data from almost anywhere whenever you need it.",
      "AWS Data Transfer Products",
      "As the name suggests, these are migration, data collection, and data transfer products that help you collect data seamlessly. They also enable you to monitor and analyze data in real-time.",
      "Amazon EC2 (Elastic Compute Cloud)",
      "This provides a secure and resizable computing capacity based on your needs. The service is designed to make web-scale cloud computing more accessible.",
      "Amazon SNS (Simple Notification Services)",
      "This is a notification tool that delivers messages to a large number of subscribers through email or SMS. You can send alarms, service notifications, and other messages intended to call attention to important information.",
      "Amazon KMS (Key Management System)",
      "This is a security tool that uses 256-bit encryption for your data. It also safeguards it from hackers and cyber attacks.",
      "Amazon Lambda",
      "This service runs your code depending on specific events and manages the dependent resources. You need neither managing nor provisioning servers, and how much you pay depends on how long it takes to execute your code. It saves a lot of money compared with services that charge hourly rates.",
      "Route 53",
      "This is a DNS service in the cloud that doesn’t require you to maintain a separate DNS account. It’s designed to provide businesses with a reliable and cost-effective method to route users to internet applications.",
      "After having learned what is AWS, let us next find out the benefits of Amazon web services.",
    ],
    Name: "Tamanna Verma",
    BlogDate: "May 15, 2021",
  },
  {
    blogId: 3,
    Category: "Technical",
    BlogHeading: "What If Data Is BIG?",
    AboutBlog:
      "Since the invention of computers, people have used the term data to refer to computer information, and this information was either transmitted or stored. But that is not the only data definition; there exist other types of data as well.",
    imgsrc: blogProfile,
    FullBlog: [
      "In order to know what is BIG DATA, you first need to know What is DATA? Since the invention of computers, people have used the term data to refer to computer information, and this information was either transmitted or stored. But that is not the only data definition; there exist other types of data as well. So, what is the data? Data can be texts or numbers written on papers, or it can be bytes and bits inside the memory of electronic devices, or it could be facts that are stored inside a person’s mind. Now, if we talk about data mainly in the field of science, then the answer to “what is data” will be that data is different types of information that usually is formatted in a particular manner. All the software is divided into two major categories, and those are programs and data. Programs are the collection made of instructions that are used to manipulate data. So, now after thoroughly understanding what is data and data science, let us learn some fantastic facts.",
      " What is BIG DATA?",
      " In Layman’s language, let’s suppose the maximum capacity of our OS is 50 Gigabytes, and let's suppose we want to store the data more than this capacity, let’s say we want to store the data of 100 Gigabytes, then if we try to store this data, our system will give an error saying -You are dumping data more than my capacity. So this is the point where the problem arises. The data we want to store is big and we don’t have enough space to store it and this problem is known as BIG DATA. We are constantly producing data — even our kitchen appliances are hooked up to the internet, sharing and storing mountains of data. The amount of information being collected around the globe is literally too hefty to process. That’s where the notion of big data comes into play. Simply put, big data consists of huge sets of raw data that are too complex for traditional data-processing software. Powerful computers and advanced software mine these data set to reveal unsuspected patterns and trends. Big data is taking the world by storm and here are I am presenting you the most fascinating Big Data statistics. There are a lot of misconceptions about Big Data, and the biggest one is that it’s simple. At first glance, Big Data appears to be just another processing issue. Surely all data trends would eventually be revealed by conventional processing on a bigger computer. But that’s not how it works. The goal of big data is to increase the speed at which products get to market, to reduce the amount of time and resources required to gain market adoption, target audiences, and to ensure that customers remain satisfied.",
      " Big Data could be found in three forms:",
      " 1. Structured",
      " 2. Unstructured ",
      "3. Semi-structured",
      " Structured",
      "Any data that can be stored, accessed, and processed in the form of fixed-format is termed as a ‘structured’ data. Over the period of time, talent in computer science has achieved greater success in developing techniques for working with such kind of data (where the format is well known in advance) and also deriving value out of it. However, nowadays, we are foreseeing issues when the size of such data grows to a huge extent, typical sizes are being in the rage of multiple zettabytes. Do you know? 1021 bytes equal to 1 zettabyte or one billion terabytes forms a zettabyte. Looking at these figures one can easily understand why the name Big Data is given and imagine the challenges involved in its storage and processing. Do you know? Data stored in a relational database management system is one example of a ‘structured’ data.",
      " Unstructured",
      "Any data with an unknown form or the structure is classified as unstructured data. In addition to the size being huge, unstructured data poses multiple challenges in terms of its processing for deriving value out of it. A typical example of unstructured data is a heterogeneous data source containing a combination of simple text files, images, videos, etc. Now day organizations have wealth of data available with them but unfortunately, they don’t know how to derive value out of it since this data is in its raw form or unstructured format.",
      " Semi-structured",
      " Semi-structured data can contain both forms of data. We can see semi-structured data as structured in form but it is actually not defined with e.g. a table definition in relational DBMS. An example of semi-structured data is data represented in an XML file.",
    ],
    Name: "Tamannah Verma",
    BlogDate: "May 15, 2021",
  },
];
const BlogList = [
  {
    CategoryName: "Technical",
    CategoryIcon: "ds",
  },
];
const TrendingBlog = [
  {
    Category: "Technical",
    BlogHeading: "What If Data Is BIG?",
    AboutBlog:
      "Since the invention of computers, people have used the term data to refer to computer information, and this information was either transmitted or stored. But that is not the only data definition; there exist other types of data as well.",
    imgsrc: blogProfile,

    Name: "Tamannah Verma",
    BlogDate: "May 15, 2021",
    blogLeftimg:
      "https://miro.medium.com/max/1000/1*tZEdL85CFLWU_FRidB0Gtw.jpeg",
    blogId: 3,
  },
  {
    blogId: 2,
    Category: "Technical",
    BlogHeading: "How Amazon.com use AWS?",
    AboutBlog:
      "Amazon Web Services (AWS) is an evolving cloud computing platform provided by Amazon. It provides a mix of infrastructure as a service (IaaS), Platform as a service (PaaS), and Packaged software as a service ..",
    imgsrc: blogProfile,
    Name: "Tamanna Verma",
    BlogDate: "May 15, 2021",
    blogLeftimg:
      "https://miro.medium.com/max/660/1*qYWKOnF1F-TpauSGcHtUfQ.jpeg",
  },
];
export { BlogData, BlogList, TrendingBlog };
